### ISSUE TITLE
highlight group style

### ISSUE THREAD

**Issue by fedoranvar** [windwp/windline.nvim#11]
Good day to you!

is it possible to set style (bold, underscore, etc.) to highlight groups in setup function?
![image](https://user-images.githubusercontent.com/52028706/135241130-ee86c5e9-d3c0-403c-b9e4-8d6a791c2026.png)

e.g. `... colors.InactiveStyle = "bold: ..."

Thank you!

**Comment by windwp** [comment]
you need to  set it when you create a highlight group { fgcolor,bgcolor, style}
colors.color_name is only a hex rgb string
you can see a sample here
https://github.com/windwp/windline.nvim/blob/36bdcd225c893f3fa507bfc3b9e68fe139c25312/lua/wlsample/bubble.lua#L29

**Comment by fedoranvar** [comment]
Thank you!
