### ISSUE TITLE
Error when executing vim.schedule: table idnex is nil

### ISSUE THREAD

**Issue by qwexvf** [windwp/windline.nvim#17]
When i launch neovim and run telescope right away it throws:

```
Error executing vim.schedule lua callback: .../dein/.cache/init.vim/.dein/lua/windline/cache_utils.lua:55: table index is nil
```

Is there something i can do to avoid this?

i can provide a minimal init.vim if you need.

**Comment by windwp** [comment]
yes can you provide it .
 maybe it happen when you lazyload plugin by dein.

**Comment by windwp** [comment]
I still don't know what happen but I think the new commit will fix that
