### ISSUE TITLE
github-nvim-theme colorscheme

### ISSUE THREAD

**Issue by SebastienWae** [windwp/windline.nvim#18]
It seems that there is an issue when using [github-nvim-theme](https://github.com/projekt0n/github-nvim-theme).

Once loaded, if I try to switch to any other colorscheme (even github-nvim-theme own variants) windline colors broke, and I have to restart to fix.

Starting colors when using github_light ✅
![screenshot](https://user-images.githubusercontent.com/55792872/138126442-fa77bc53-62a8-453c-8724-1091867bf8ca.png)

When trying to switch to darkblue ❌
![screenshot2](https://user-images.githubusercontent.com/55792872/138126580-432b7152-1a79-4586-8bbe-f4223d39f98a.png)

When trying to switch to github_dark ❌
![screenshot3](https://user-images.githubusercontent.com/55792872/138126647-5445703b-fc71-4904-bad7-499fdca96777.png)

Otherwise, it's working when I'm not loading [github-nvim-theme](https://github.com/projekt0n/github-nvim-theme). Any idea what can cause this?

**Comment by windwp** [comment]
it work
```lua
    -- you need set background because github-theme don't set it on setup
    -- function
    vim.api.nvim_command([[set background=dark]])
    require('github-theme').setup({
        theme_style= 'dark' -- can be reproduce with any theme style: dark/dark_default/dimmed/light/light_default
    })
    require('wlsample.evil_line')

```

you can make your own color for github_dark by create a lua file on  
$HOME/.config/nvim/lua/windline/theme/github_dark.lua
https://github.com/windwp/windline.nvim/blob/master/lua/windline/themes/gruvbox.lua

**Comment by SebastienWae** [comment]
The issue is not with the dark version, but switching from dark to light or light to dark.

Try again with the init you used and then do:
```vimL
:set background=light
:lua require('github-theme').setup({theme_style = 'light'})
```

![screenshot1](https://user-images.githubusercontent.com/55792872/138240101-72db7a01-61aa-4273-a819-7e447b24748c.png)
