### ISSUE TITLE
[Feature Request] Dynamic add section

### ISSUE THREAD

**Issue by ray-x** [windwp/windline.nvim#2]
This is for integrate with other plugins

e.g. To add a status line section for plugin runs unit test:

```lua
require'windline'.add_section({get_test_progress={get_test_progress(), 'white'}})
```
And once test completed
```lua
require'windline'.remove_section('get_test_progress')
```

Or add animation

```lua
animation.add_animation({get_test_progress = {
    timeout = 3000,
    delay = 200,
    interval = 150,
    effect = efffects.list_text(get_test_progress),
    on_tick = function(value)
       get_test_progress()
    end
}})
```
And remove animation on test finish callback
```lua
animation.remove_animation('get_test_progress')
```

**Comment by windwp** [comment]
hi I add some functions to add or remove components.
sample here
https://github.com/windwp/windline.nvim/blob/d4d628f23e19845754b97db96fac7fa75a00ce84/lua/wlsample/test_add_component.lua#L282

about add animation I still not figure out how to do it a simple way because the component can have a child component with highlight and the animation need to understand the structure of the component.

**Comment by ray-x** [comment]
I am trying to call ` lua require'wlsample/test_add_component'` But did not see 🧛 shows in status bar.
Anything wrong?

**Comment by windwp** [comment]
hi you need to press key leader-x to add and leader-z to remove

**Comment by ray-x** [comment]
Cool, I see how it works. Thanks!
Is it possible to add text animation as well?  (e.g. a progress bar)

**Comment by windwp** [comment]
https://github.com/windwp/windline.nvim/blob/master/lua/wlsample/job_test.lua#L69

you can try this. It run command `sleep 10` .when command is running it display spinner and after that command finish you can get the text and display on status

 I think the easy way is to write your component animation inside the `text` function and set  variables on buffer to display animation and after your task finish you can change those variables to display a result

**Comment by ray-x** [comment]
```
job_utils.job_event(
        'sleep 10',
        'BufEnter',
        'job_sleep',
        function(data)
            if data.is_load then
                return 'event ' .. data.loading_text
            end
            return 'bufenter done ' .. (data.data or '')
        end
    ),
```

job_event require a system command. But lots of time I may run an async function from lua. e.g.   `require"go.format".import()`  And it will use underlie lsp async request.   So `sleep 10s` will not be accurate.  Is it possible to create a hook or event-driven way to update the status line?

Also. let say run `yarn test` I still prefer my plugin control the workflow and output. That means I will not run it through  `job_event`. If the user installed windline, the output may rout to windline if it is enabled by config.

**Comment by windwp** [comment]
yeah i know it that why i suggest to use a buffer variable

**Comment by ray-x** [comment]
Not sure how it going to work.

If I am going to add a status show status of unit test. I will have a
|spinner|status indicator|message

Spinner will need to auto-update every 50ms until test finish
status indicator and message will be based on output of unit test.

I can update the global variable or buffer variable in the plugin.
How will I achieve this with `job_event`?

**Comment by windwp** [comment]
https://github.com/windwp/windline.nvim/blob/be5ae176a57be9191095e848261bf7f6156997ba/lua/wlsample/job_test.lua#L92

I add a sample here just change vim.g.tmp_job_state and that component will change.

**Comment by ray-x** [comment]
Nice! That looks like the one I am looking for. Thanks!
