### ISSUE TITLE
Buffer is not 'modifiable' error

### ISSUE THREAD

**Issue by pwntester** [windwp/windline.nvim#24]
Hi,

Im getting this error when calling `:PackerSync` so I guess its related with trying to write to any of the Packer buffers?

```
Error executing vim.schedule lua callback: ...pack/packer/start/windline.nvim/lua/wlfloatline/init.lua:194: Buffer is not 'modifiable'
```

My configuration is https://github.com/pwntester/dotfiles/blob/master/config/nvim/lua/plugins/windline.lua

Thanks!

**Comment by windwp** [comment]
hi 
in your config don't run a job inside a text function it will run every time you typing a key.
if you want to run a job you can run a cache component so it only run 1 when an event happen. 

https://github.com/windwp/windline.nvim/wiki/component#cache-value-on-buffer.
you can run WindLineBenchmark to check.


about your issue  i don't use packer but i try to run packersync but it not happen.

**Comment by pwntester** [comment]
Thanks! caching the git branch and github repo improve the responsiveness a lot and also got rid of the `Buffer is not 'modifiable'` error so it was probably some sort of race condition
