### ISSUE TITLE
Enable temporary hiding the float status line

### ISSUE THREAD

**Issue by pwntester** [windwp/windline.nvim#25]
Hi,

I have set up the status line as a float using:

```
require("wlfloatline").setup {
  interval = 300,
  ui = {
    active_char = "▁",
    active_color = "line_bg",
    active_hl = "Error",
  },
  skip_filetypes = {
    "NvimTree",
  },
}
```

The problem is that some windows pickers such as the one implemented by [NvimTree](https://github.com/kyazdani42/nvim-tree.lua/blob/master/lua/nvim-tree/lib.lua#L291-L310) will use the status line to display a code to use to pick that window. Therefore, I want to hide the float windline when the picker is called and restore it again after the window has been selected. I tried using `WindLineFloatToggle` but its not doing anything. My guess is that it gets rendered again by some autocmd. Would it be possible to disable those autocmds when the windline is supposed to be hidden?

Thanks!

**Comment by windwp** [comment]
https://github.com/windwp/windline.nvim/issues/21#issuecomment-953386547
