### ISSUE TITLE
lines is a nil value (line 223 of windline/init.lua)

### ISSUE THREAD

**Issue by ESilva15** [windwp/windline.nvim#26]
It's an easy fix, locally I just added an if statement to check if the variable `lines` around the block of code in that function.
If one of the contributors feels like adding it, go ahead!

**Comment by windwp** [comment]
Thank for your report i will fix that.
are you calling the add_status function directly?

**Comment by ESilva15** [comment]
Nope, I was getting that error by simply calling the setup() function.
`require('windline').setup({tabline = {}})`
Nothing esoteric
