### ISSUE TITLE
Could you provide some default/preconfigured settings?

### ISSUE THREAD

**Issue by nyngwang** [windwp/windline.nvim#27]
I don't know how to setup :( I have tried this one but I didn't see the wind animation:

```
config = function ()
  require('wlsample.wind')
end
```

Could it be something like this?

```
config = function ()
  require('windline').setup {
    predefined: 'some_cool_default'
  }
end
```

**Comment by windwp** [comment]
https://github.com/windwp/windline.nvim#included-status-lines

**Comment by nyngwang** [comment]
I don't know how to put the section you linked into the `require('windline').setup { ... }`. And it seems that if I provide nothing to the `...` I will get error during plugin-installation of packer.nvim

**Comment by windwp** [comment]
you dont' need to use setup  function just  require a sample statusline.

if you want to modify it. You need copy sample  config to your nvim config folder and modify it.
https://github.com/windwp/windline.nvim/blob/master/lua/wlsample/evil_line.lua
Please read REAME.

**Comment by nyngwang** [comment]
OK cool. Most of the plugins tolding me to call the `setup { ... }` after installation. So I don't have to add the `config = function() ... end` field in my packer.nvim settings?

**Comment by windwp** [comment]
it have a setup function but it has too many line so i create a new file.

**Comment by nyngwang** [comment]
This project is fukcing awesome WOOW!
