### ISSUE TITLE
Airline_anim doesn't autostarted 

### ISSUE THREAD

**Issue by ruanyouxing** [windwp/windline.nvim#29]
i used airline_anim in wlsample and the antimations didn't run automatically until i execute a command in Command mode

**Comment by windwp** [comment]
what is the command . you can checking  code and it can toggle by key <leader>u9

**Comment by ruanyouxing** [comment]
every commands. Example like :w,:NvimTreeToggle,:noh,:Telescope,etc..,but i have to run it once,then it just shows up animations

**Comment by windwp** [comment]
i don't know any reason  why that happen so you can try to copy that  airline_anim to your config and modify.
