### ISSUE TITLE
Any ideas of this table overflow error?

### ISSUE THREAD

**Issue by ray-x** [windwp/windline.nvim#30]
Not sure anyone see this before:

```
Error executing vim.schedule lua callback: table overflow                                                                                                                          
stack traceback:                                                                                                                                                                   
        [C]: in function 'insert'                                                                                                                                                  
        ...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:95: in function 'render_comp'                                                                                  
        ...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:121: in function 'render_float_status'                                                                         
        ...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:196: in function 'tick'                                                                                        
        ...k/packer/opt/windline.nvim/lua/wlanimation/animation.lua:82: in function ''                   
```

It is the first time I saw this.  

If comp.text() function through an error, will this happen? Some time I saw this error:
```
Error executing vim.schedule lua callback: ...ker/opt/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:23: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
	[C]: in function 'sub'
	...ker/opt/nvim-treesitter/lua/nvim-treesitter/ts_utils.lua:23: in function 'get_node_text'
	.../pack/packer/opt/nvim-treesitter/lua/nvim-treesitter.lua:40: in function 'get_line_for_node'
	.../pack/packer/opt/nvim-treesitter/lua/nvim-treesitter.lua:72: in function 'statusline'
	~/.config/nvim/lua/modules/ui/eviline.lua:83: in function 'current_treesitter_context'
	~/.config/nvim/lua/modules/ui/eviline.lua:105: in function 'current_function'
	~/.config/nvim/lua/modules/ui/eviline.lua:344: in function 'text'
	...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:76: in function 'render_comp'
	...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:114: in function 'render_float_status'
	...e/pack/packer/opt/windline.nvim/lua/wlfloatline/init.lua:179: in function 'tick'
	...k/packer/opt/windline.nvim/lua/wlanimation/animation.lua:82: in function ''
	vim.lua: in function <vim.lua:0>⏎                                                 
```
Not sure if those two related.

**Comment by windwp** [comment]
can you share your config and WindLineBenchmark result

**Comment by ray-x** [comment]
This issue is not easy to reproduce. And I am not sure if it caused by windline or other plugins that corrupt the memory.

My windlineBenchmark:
```
Status:
%#WLred_black#▊  %#WLmagenta_NormalBg#  master%#WLNormalFg_NormalBg#29.91k %#WLmagenta_NormalBg#elastic_search_query_executor.go  %#WLred_NormalBg#  0%#WLyellow_b_NormalBg#  24%#WLblue_NormalBg#  0%#WLNormalFg_NormalBg# %#WLgreen_light_NormalBg#🐼%#WLNormalFg_NormalBg#  %#WLgreen_b_NormalBg#  func (esqe *ElasicSearchQueryExecutor) ExecuteCombinedSegmentsCou%#WLNormalFg_NormalBg# %= %3l:%-2c %3p%% %#WLblue_NormalBg#▃▃%#WLmagenta_NormalBg# null-ls|gopls %#WLgreen_NormalBg# 0%#WLred_NormalBg#  0%#WLblue_NormalBg# 柳0%#WLNormalFg_NormalBg# %#WLblue_NormalBg# inte/doma/execr%#WLNormalFg_NormalBg#  %#WLred_black#▊
Time:
render 10000 time : *1.65144345*
Comp:
          time         name num    text
01 *0.030331802*              10000 - %#WLred_black#▊
03 *0.03400991*      vi_mode 10000 - %#WLred_black#  
04 *0.004638201*              10000 - %#WLmagenta_NormalBg#  master
05 *0.024150287*         file 10000 - %#WLNormalFg_NormalBg#29.91k %#WLmagenta_NormalBg#elastic_search_query_executor.go  
06 *0.01601366*   diagnostic 10000 - %#WLred_NormalBg#  0%#WLyellow_b_NormalBg#  0%#WLblue_NormalBg#  0
07 *0.005702096*    signature 10000 - %#WLNormalFg_NormalBg# %#WLgreen_light_NormalBg#🐼%#WLNormalFg_NormalBg# 
08 *0.449944048*     funcname 10000 - %#WLNormalFg_NormalBg# %#WLgreen_b_NormalBg#  func (esqe *ElasicSearchQueryExecutor) ExecuteCombinedSegmentsCou%#WLNormalFg_NormalBg# 
09 * 0.0015075*              10000 - %=
10 *0.00315237*              10000 - %#WLNormalFg_NormalBg# %3l:%-2c 
11 * 0.0198207*              10000 - %3p%% %#WLblue_NormalBg#▃▃
12 *0.002764212*              10000 - %#WLmagenta_NormalBg# null-ls|gopls
13 *0.039128698*          git 10000 -  %#WLgreen_NormalBg# 0%#WLred_NormalBg#  0%#WLblue_NormalBg# 柳0
14 *0.430337154*       folder 10000 - %#WLNormalFg_NormalBg# %#WLblue_NormalBg# inte/doma/execr%#WLNormalFg_NormalBg# 
15 *0.010041936*              10000 - %#WLNormalFg_NormalBg# 
16 *0.031752759*              10000 - %#WLred_black#▊
```
My setup:
https://github.com/ray-x/nvim/blob/master/lua/modules/ui/eviline.lua

And this:
https://github.com/ray-x/nvim/blob/647175967b8ecd34758620cbae7cdd5408320421/lua/core/lazy.lua#L185-L187

I am adding more logs to both nvim-treesitter and windline to see what was going on and hope I can bring more info.

**Comment by windwp** [comment]
you can use cache component on component "folder" so it don't calculate everytime status draw.
https://github.com/ray-x/nvim/blob/master/lua/modules/ui/eviline.lua#L319.
https://github.com/windwp/windline.nvim/wiki/component#cache-value-on-buffer

and move require to outside of text function because require on impatient do a lot of thing
https://github.com/ray-x/nvim/blob/master/lua/modules/ui/eviline.lua#L85.

maybe it improve performance a bit but i am not sure it is fixed your issue. 
it fix another strange issue  #24  so you can try.

**Comment by ray-x** [comment]
I am dumping logs here:

```lua
      if text and text ~= "" then
        if #state.text_groups > 100 then
          lprint(state.text_groups)
        end
        table.insert(state.text_groups, {
          text = text:gsub("%%%%", "%%"),
          hl = comp:make_hl(hl, hl_data.default),
        })
      end
```
Please refer to the log. 
You can see state.text_groups is growing over the period

[error_Head.log](https://github.com/windwp/windline.nvim/files/7742336/error_Head.log)

I can see the plugin will reset it to `{}`. But for some reason, it did not reset and keep growing until it overflow.

**Comment by ray-x** [comment]
My theory is one of the components was blocked and failed to response in 300ms tick. This makes the request piled up and blow off the stack.

**Comment by windwp** [comment]
interesting. how do you reproduce it :)

**Comment by ray-x** [comment]
I have about 10 nvim instances opened. And each one may open a git repo/project( lua, go, javascript etc). I leave them alone and only check back every 1 hour or two. And after ~3 hours, one instance crash with the overflow error.

**Comment by windwp** [comment]
can you try to use branch thread.

**Comment by ray-x** [comment]
I am using thread branch now. Will keep you posted.

**Comment by ray-x** [comment]
I am afraid it was not fixed
I log the items and state here:
```lua
local function render_float_status(bufnr, winid, items)
  state.comp = {}
  state.mode = mode()
  Comp.reset()
  local total_width = vim.o.columns
  local status = ""
  local cur_position = 0
  state.text_groups = {}
  state.thread_id = state.thread_id + 1
  for _, comp in pairs(items) do
    if #state.text_groups > 50 and #state.text_groups < 200 then
      lprint(items, state)
    end
 ...
```

And the log is attached:

[windline.log](https://github.com/windwp/windline.nvim/files/7749292/windline.log)

From the logs I can see text_groups has duplicate items and it is growing after a few hours. 
Maybe we should either add a mutex to text_groups. Or use map instead of array. Or maybe pass it through instead of use it as a global object.

**Comment by windwp** [comment]
it already a global object.
`lua print(vim.inspect(WindLine.state.text_groups)`

**Comment by windwp** [comment]
```lua
{
      hl = "WLred_black",
      text = "▊"
    }, {
      hl = "WLred_black",
      text = "  "
    }, {
      hl = "WLmagenta_NormalBg",
      text = "  master"
    }, {
      hl = "WLNormalFg_NormalBg",
      text = "5.06k"
    }, {
      hl = "",
      text = " "
    }, {
      hl = "WLmagenta_NormalBg",
      text = "SegmentContext.js "
    }, {
      hl = "",
      text = " "
    }, {
      hl = "WLred_black",
      text = "▊"
    }, {
      hl = "WLred_black",
      text = "  "
    }, {
      hl = "WLmagenta_NormalBg",
      text = "  master"
    }, {
      hl = "WLNormalFg_NormalBg",
      text = "5.06k"
    }, {
      hl = "",
      text = " "
    }, {
      hl = "WLmagenta_NormalBg",
      text = "SegmentContext.js "
    }, {
      hl = "",
      text = " "
    }, {
      hl = "WLred_black",
      text = "▊"
    }, {
      hl = "WLred_black",
      text = "  "
    }, {
      hl = "WLmagenta_NormalBg",
      text = "  master"
    }, {
      hl = "WLNormalFg_NormalBg",
      text = "5.06k"
    }, {
```

 i think it happen on diagnostic component. after the file name component 
``` 
{
      hl = "WLmagenta_NormalBg",
      text = "SegmentContext.js "
    },
``
 it can continue to display another component.

**Comment by ray-x** [comment]
Both of which is from lsp. The position/file does not have either diagnostic info nor lsp signature. So it is ok for those fields to be empty.

**Comment by windwp** [comment]
I try to lock thread_id on a tick function and add reset text_group when it  have different thread_id. maybe it work

**Comment by ray-x** [comment]
Sure, I will give it another try. Thanks!

**Comment by windwp** [comment]
@ray-x  i disable update floatline when nvim lost focus.

**Comment by ray-x** [comment]
In fact, in yesterday's version, I can still see the text_groups growing, but it stopped at 60 instead of going all the way to blow off table length limitation.
I will try your new version and see how it works.

**Comment by ray-x** [comment]
I am still seeing the same thing today. No overflow, but text_groups size can grow over 50.

**Comment by windwp** [comment]
it still happen on inactive time?

**Comment by ray-x** [comment]
It happened when I re-enter the inactive nvim instance this time.

**Comment by windwp** [comment]
it happen on inactive time and after display diagnostic component
so think it similar to that
https://github.com/nvim-lualine/lualine.nvim/issues/462
https://github.com/neovim/neovim/issues/16501
are you use mac ? maybe it have a problem with lua on mac to restore memory.

**Comment by windwp** [comment]
I still merge that to save some CPU power on inactive time :).
but i think it is a problem on upstream

**Comment by ray-x** [comment]
Yes. I agree it might be related. I am using MacOS. 
It annoyed me earlier because when table overflow, the nvim instance was frozen and used lots of memory (>8G virtual memory) and I have to kill it manually.
So far that issue does not happen. You can mark it as upstream and close the issue.
Thanks for your help.

**Comment by windwp** [comment]
ok i merge it to master

**Comment by ray-x** [comment]
Verified on master.
