### ISSUE TITLE
Windline floating window stops updating when setting interval to zero

### ISSUE THREAD

**Issue by JuniorSuperTux** [windwp/windline.nvim#31]
Windline stops updating when using the following config:
```lua
require('wlfloatline').setup({
    interval = 0
})
```
However, it still updates when entering command mode (with a small delay).

Everything works after changing the interval to 1, but the command mode delay still exists. It does not delay when floating window is not enabled.

Also, sometimes when I enter Neovim, this error shows:
```
E5108: Error executing lua [string "v:lua"]:1: attempt to call field 'floatline_show' (a nil value) 
```

**Comment by windwp** [comment]
better use interval >200. interval is millisecond second and 0 mean no update.

**Comment by JuniorSuperTux** [comment]
What about the entering command disables floating window issue? Also that error message

**Comment by windwp** [comment]
enter command disable floating window because some command will print output and floating window will hide it.
i don't have that issue so you need provide how to reproduce it.
