### ISSUE TITLE
The autocmd `CursorHold` will fail if animation is triggered

### ISSUE THREAD

**Issue by nyngwang** [windwp/windline.nvim#34]
As title. I'm using `require('wlsample.airline_anim')`, and my config are these:

```
use {
  'windwp/windline.nvim',
  config = function ()
    require('wlsample.airline_anim')
  end
}
vim.keymap.set('n', '<Leader>w', function()
  WindLine.airline_anim_toggle()
end, NOREF_NOERR_TRUNC)
```

If I enter the animation mode with `<Leader>w`, then the following autocmd will fail:

```
vim.cmd [[autocmd CursorHold,CursorHoldI * lua vim.diagnostic.open_float(nil, {focus=false, scope="cursor"})]]
```

i.e. there will be no auto-hover anymore.

---

`nvim -v`:

```
NVIM v0.7.0-dev+886-ga88046fe2
Build type: Release
LuaJIT 2.1.0-beta3
```

I experience this after the lastest update on branch `master`.

**Comment by nyngwang** [comment]
This seems to be related to a tricky old issue from NeoVim I linked. I just resolved this with another plugin (mentioned in the linked thread) as a temporary solution.

**Comment by windwp** [comment]
i don't have this issue it still display popup when animation is running. i use neovim 0.7 linux
but you already find a solution for this or maybe you can disable animation when working.

**Comment by nyngwang** [comment]
I will never diable it during my work :) It helps me focus.
