### ISSUE TITLE
Windline is_git() broken on nightly

### ISSUE THREAD

**Issue by danielnehrig** [windwp/windline.nvim#35]
```
local git_comps = require("windline.components.git").is_git()
```
`got_comps` is false when inside a git repo
works on 0.6.1 just fine but on 0.7.0 nightly it breaks and does not work

**Comment by windwp** [comment]
you need add bufnr .is_git(bufnr)

**Comment by danielnehrig** [comment]
> you need add bufnr .is_git(bufnr)

true not it works
