### ISSUE TITLE
Exception thrown when attempting to run benchmark

### ISSUE THREAD

**Issue by EtiamNullam** [windwp/windline.nvim#45]
Exception is thrown when attempting to run benchmark using `:WindLineBenchmark`:

```
E5108: Error executing lua C:\Users\user\.vim-plug\plenary.nvim/lua/plenary/profile/p.lua:46: module 'jit.vmdef' not found:
	no field package.preload['jit.vmdef']
	no file 'C:\Users\user\scoop\apps\lua\current'
	no file 'C:\Users\user\scoop\apps\lua\current'
	no file 'C:\Users\user\scoop\apps\lua\current'
stack traceback:
	[C]: in function 'require'
	C:\Users\user\.vim-plug\plenary.nvim/lua/plenary/profile/p.lua:46: in main chunk
	[C]: in function 'require'
	C:\Users\user\.vim-plug\plenary.nvim/lua/plenary/profile.lua:5: in main chunk
	[C]: in function 'require'
	...ers\user\.vim-plug\windline.nvim/lua/windline/benchmark.lua:9: in function 'benchmark'
	[string ":lua"]:1: in main chunk
```

Different exception is thrown when attempting to run a second time, not sure if helpful:

```
E5108: Error executing lua ...ers\user\.vim-plug\windline.nvim/lua/windline/benchmark.lua:9: loop or previous error loading module 'plenary.profile'
stack traceback:
	[C]: in function 'require'
	...ers\user\.vim-plug\windline.nvim/lua/windline/benchmark.lua:9: in function 'benchmark'
	[string ":lua"]:1: in main chunk
```

NVIM v0.7.0
Windows 10

**Comment by windwp** [comment]
are you try on WSL I think it only work on linux

**Comment by EtiamNullam** [comment]
Sadly I don't use WSL so I can't say if it works there. I think benchmark would be useful.

**Comment by windwp** [comment]
you can go to that file and comment line 1 to 20
C:\Users\user\.vim-plug\plenary.nvim/lua/plenary/profile/p.lua:46
https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/profile.lua#L23

or submit a PR to benchmark without plenary

**Comment by EtiamNullam** [comment]
Looks like commenting these lines (`46 - 68` in `p.lua`) like you suggested really made it work for me!

So is it just a chunk of plenary that doesn't really work on Windows? If so it might be useful to raise an issue on plenary repository.
