### ISSUE TITLE
Are you planing to support winbar?

### ISSUE THREAD

**Issue by fahimfaisal42** [windwp/windline.nvim#47]
I know its still in early stage but the winbar could make for some cool features if supported...

**Comment by windwp** [comment]
you can try this

```

**Comment by EpsilonKu** [comment]
Is it possible to filter it? It shows one telescope

**Comment by ray-x** [comment]
A working example like this ?
https://gist.github.com/s1n7ax/3d2b476ecbde72693572b8652044e5a4

I tried with steps in wiki (https://github.com/windwp/windline.nvim/wiki/Winbar) but not working for me

**Comment by windwp** [comment]
> A working example like this ? https://gist.github.com/s1n7ax/3d2b476ecbde72693572b8652044e5a4
> 
> I tried with steps in wiki (https://github.com/windwp/windline.nvim/wiki/Winbar) but not working for me

maybe you call add_status before setup()


@EpsilonKu  i fixed the problem with float window

**Comment by ray-x** [comment]
I am using this to add winbar
```lua
local winbar = {
  filetypes = { "winbar" },
  active = {
    { " " },
    { "%=" },
    {
      "@@",
      { "red", "white" },
    },
  },
  inactive = {
    { " ", { "white", "InactiveBg" } },
    { "%=" },
    {
      function(bufnr)
        local bufname = vim.api.nvim_buf_get_name(bufnr)
        local path = vim.fn.fnamemodify(bufname, ":~:.")
        return path
      end,
      { "white", "InactiveBg" },
    },
  },
}

windline.setup({
  colors_name = function(colors)
    --- add more color

    local mod = function(c, value)
      if vim.o.background == "dark" then
        return HSL.rgb_to_hsl(c):tint(value):to_rgb()
      end
      return HSL.rgb_to_hsl(c):shade(value):to_rgb()
    end

    local normalFg, normalBg = require("windline.themes").get_hl_color("StatusLine")

    -- this color will not update if you change a colorscheme
    -- colors setup
    return colors
  end,
  statuslines = { default, winbar, quickfix, explorer },
})
-- also tried this:
windline.add_status(winbar)

```

**Comment by windwp** [comment]
i add that code for winbar above to wlsample.evil_line and it working. are you sure you update  plugin :)
