### ISSUE TITLE
background of statusline becomes #303030 with a low enough value for color hex

### ISSUE THREAD

**Issue by zoefiri** [windwp/windline.nvim#49]
# configs 
my "theme" (it's just a modification of evil-line):
https://gist.github.com/4f0bafffa81e23b445fe31d02b02381e

and here's my windline setup:
https://gist.github.com/dad544ecceea50ecce53326174fb24a1

# problem
I can set theme colors as relatively "large" hex values and they work fine but using smaller ones (darker colors) seemingly just substitutes the color I want for plain gray, so far seemingly #262626 and #303030

I know both are really messy but at the moment I'd just like to get this working. the colors_name func is reading in colors from a directory full of text files with colors in them, I know it's a really sloppy system but my theming stuff still kinda uses this (it's related to an old script I wrote but don't use anymore).

creating a color "test" and then setting the normal mode background to it these are the results:

#ff0000:
![image](https://user-images.githubusercontent.com/27149384/172951615-8743f8e5-7c05-466d-b574-8f95a4a2356d.png)

#3a0000:
![image](https://user-images.githubusercontent.com/27149384/172951884-d8332d55-0d36-45b8-af15-4e4c675b57c6.png)

#390000:
![image](https://user-images.githubusercontent.com/27149384/172952036-77588f78-56ad-44f0-9984-9c7539acbd2a.png)

Somehow a red value under 3a results in it just becoming black, how can I prevent this???

**Comment by windwp** [comment]
Can you check it has the correct value by run command `highlight WL{bg}_{fg}` sample `highlight WLc1_black`

```lua
local default = {
      filetypes={'default'},
      active={
      },
      inactive={
      }
   }

   local explorer = {
      filetypes = {'fern', 'NvimTree','netrw'},
      active = {
         {' ', {'white', 'black'} },
      },
      --- show active components when the window is inactive
      always_active = true,
      --- It will display a last window statusline even that window should inactive
      show_last_status = true
   }
   local windline = require('windline')
   windline.setup({
      statuslines = {
         explorer, {require('plugconfs.windline-custom-theme')}
      }
   })
```
is that file https://gist.github.com/zoefiri/dad544ecceea50ecce53326174fb24a1 name  'plugconfs.windline-custom-theme`
if i am right you only need to use.
```
require('plugconfs.windline-custom-theme')
```

**Comment by zoefiri** [comment]
> Can you check it has the correct value by run command `highlight WL{bg}_{fg}` sample `highlight WLc1_black`
> 
> ```lua
> local default = {
>       filetypes={'default'},
>       active={
>       },
>       inactive={
>       }
>    }
> 
>    local explorer = {
>       filetypes = {'fern', 'NvimTree','netrw'},
>       active = {
>          {' ', {'white', 'black'} },
>       },
>       --- show active components when the window is inactive
>       always_active = true,
>       --- It will display a last window statusline even that window should inactive
>       show_last_status = true
>    }
>    local windline = require('windline')
>    windline.setup({
>       statuslines = {
>          explorer, {require('plugconfs.windline-custom-theme')}
>       }
>    })
> ```
> 
> is that file https://gist.github.com/zoefiri/dad544ecceea50ecce53326174fb24a1 name 'plugconfs.windline-custom-theme` if i am right you only need to use.
> 
> ```lua
> require('plugconfs.windline-custom-theme')
> ```

![image](https://user-images.githubusercontent.com/27149384/172959691-ce51799c-99db-47d6-a1d0-efe16d3e4376.png)
ah. I'm stupid. It's because it's trying to round it to a terminal color because I'm not using `termguicolors`, is it possible to set cterm colors instead? My neovim customization uses terminal colors. Kinda forgot about that.

**Comment by zoefiri** [comment]
nvm, just realized that that doesn't work. (Unless I'm mistaken) it was pretty easy to implement myself though and it's working now,
![image](https://user-images.githubusercontent.com/27149384/172963274-39a974c5-5465-449c-b3b0-1f36b41838c4.png)


 would you like a PR for that?

**Comment by windwp** [comment]
yes you can make a PR .maybe  just check it inside function rgb2cterm .

btw nice setup
