### ISSUE TITLE
status line floating window is not shifting up when cmdheight is set to 0 in latest neovim nightly

### ISSUE THREAD

**Issue by ratheesh** [windwp/windline.nvim#54]
In the latest nightly(`2a3cb089`) of NeoViM, setting `cmdheight` to `0` and entering the cmd mode, windline floating window is not shifting up appropriately.

In the following image, bottom line is windline status line(one line above the windline statusline is from wilder)
<img width="235" alt="image" src="https://user-images.githubusercontent.com/70958/192206626-3871febe-cbdd-4802-b9f9-8e9885056a9a.png">

Can you please check this?

**Comment by windwp** [comment]
are you say about floatline? why not use a global statusline by set laststatus=3

**Comment by ratheesh** [comment]
@windwp, I have set `laststatus` to `3`.

**Comment by ratheesh** [comment]
I am closing this as this issue is no longer observed with latest commit(`c7e74f788`) on Neovim's master branch.
