### ISSUE TITLE
How does re-rendering the statusline work?

### ISSUE THREAD

**Issue by starptr** [windwp/windline.nvim#56]
I was reading through the project and I was wondering how you implemented statusline redrawing? Does it call `redraw!` on every tick? Does it draw the entire statusline or are there optimizations that allow only the changed parts to be redrawn? Thanks!

**Comment by windwp** [comment]
it update base on neovim. We don't call redraw or update status line. when neovim redraw they will call windline update. 

```lua
local count = 0
comps.count = { function()
    count = count + 1;
    return count
end,
    { 'white', 'black' }
}
```
you can test by add a simple count component.

even when neovim redraw windline doesn't update the whole status line.
you can use a  cache component to reduce update
https://github.com/windwp/windline.nvim/wiki/component#cache-value-on-buffer

**Comment by starptr** [comment]
What does neovim call when it wants to redraw, and does it know how often to redraw?

**Comment by windwp** [comment]
it will call a function you define on vim.o.statusline. 
it call when you typing any key or an autocmd  event change anything on your screen.
so if you don't change anything it will not update.

**Comment by starptr** [comment]
I see, is it drawn when [this `tick()` function is called](https://github.com/windwp/windline.nvim/blob/047c6175e7871cd17e79f1c53f923f6695370bbe/lua/wlanimation/animation.lua#L82-L82)? I'm a bit confused because I'm not sure where this variable is assigned; is this function the one that assigns to `vim.o.statusline`?

**Comment by windwp** [comment]
i already tell that it don't call redraw. it is depend on neovim. you don't need that animation part to make statusline working.

the animation of color working because on the tick we change the highlight color by call nvim_set_hl then neovim know the screen is change and it will redraw. it is the same mechanic of when you typing a key.

so the idea is we don't call redraw we just tell neovim the screen is change and neovim will do that job

**Comment by starptr** [comment]
Oh I finally understand, the animation works because neovim detects something has changed due to the `nvim_set_hl` call by windline. I guess that means changing text will not work with this strategy :(. Thanks for the help anyways!
