### ISSUE TITLE
[Feature] register and push message to status bar 

### ISSUE THREAD

**Issue by ray-x** [windwp/windline.nvim#57]
I want to push messages to a statusline component. To do that, I need
1) The plugin provides a API so I can push message through
2) It will reset back to empty after timeout (e.g. 5sec)
3) I can limit the size (width) of message

Here is an example:
I run a unit test for a package. The output is 
`test 1 done`
`test 2 done`
...
`test finished`

I has a callback hook to stdout for each message, I do
```lua
require('windline').push('component_show_test_result', 'test 1 done')
```

**Comment by windwp** [comment]
hi i think it is more customize to do that on your side
``` 
-- copy from noice
local function debounce(ms, fn)
    local timer = vim.loop.new_timer()
    return function(...)
        local argv = vim.F.pack_len(...)
        timer:start(ms, 0, function()
            timer:stop()
            vim.schedule_wrap(fn)(vim.F.unpack_len(argv))
        end)
    end
end

local message = {
    text = "",
    level = ""
}

local test_message = {
    hl_colors = {
        error = { 'red', 'NormalBg' },
        warning = { 'yellow', 'NormalBg' }
    },
    text = function()
        return {
            { message.text, message.level }
        }
    end
}
local setEmpty = debounce(8000, function() message = { text = "", level = "" } end)

_G.status_notify = function(msg, level)
    message = {
        text = msg,
        level = level
    }
    setEmpty()
end

require('windline').add_component(test_message, {
    name = "dynamic_message",
    auto_remove = true,
    position = "right"
})

```
 you can call _G.status_notify('Hello','error'). 
Adding something like this on my plugin is not necessary and it will limit about customize so i will not add this.

**Comment by ray-x** [comment]
Sure, this should work. Thanks!
