### ISSUE TITLE
Any chance of modifying this to work with lazy.nvim?

### ISSUE THREAD

**Issue by badloop** [windwp/windline.nvim#60]
Appears to work somewhat, but have to just load the defaults and then set it to disabled in the loader for the module with lazy.nvim.  It still loads and runs, but doesn't run any of the config so just left with the defaults.

I can provide more details if you'd like.

**Comment by windwp** [comment]
i try with nvim that `nvim -u lazy.lua` and it work

```
-- file lazy.lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable", -- latest stable release
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "windwp/windline.nvim",
        config = function()
            require('wlsample.airline')
        end,
    }
}, {})
```

**Comment by badloop** [comment]
This is my fault, I was making a stupid mistake in my config.  Thank you for the reply, it helped me get it sorted!
