### ISSUE TITLE
Double "##" in colors s

### ISSUE THREAD

**Issue by danielnehrig** [windwp/windline.nvim#61]
I'm migrating to lazy at the moment
and I kept getting this error which complains about the hex not being a valid hex color when trying to run
on this line https://github.com/windwp/windline.nvim/blob/66badcb002c91f6d4bfc11726c988441a3aada6c/lua/windline/utils.lua#L78
the `color` parameter contains two '##" I searched through my whole codebase that could create a double '##" but could find nothing
using packer it works just fine.

```lua
windline.setup({
  colors_name = function(colors)
    -- colors contains strings with hex colors that look like this: ##ffffff
  end
})
```

my current workaround
```lua
windline.setup({
  colors_name = function(colors)
    for k, v in pairs(colors) do
      colors[k] = string.gsub(v, "##", "#")
    end
    return colors
  end
 })
```

the pr that bricks it for me (i know you probably don't want to look at this but yeah provided it anyways)
https://github.com/danielnehrig/nvim/pull/20/files
my master with packer works just fine

**Comment by windwp** [comment]
maybe because this line
https://github.com/windwp/windline.nvim/blob/master/lua/windline/themes/init.lua#L48 
i am not use lazy.nvim right now so i am not sure about that.
can you try run this
```
lua vim.print(require('windline.themes').get_hl_color('Normal'))
```

**Comment by danielnehrig** [comment]
i have no clue what happend the issue fixed itself auto magically nothing changed code wise after creating the issue
sorry for wasting your time and thanks for the fast response
