### ISSUE TITLE
Is italic / boldItalic text supported?

### ISSUE THREAD

**Issue by azolus** [windwp/windline.nvim#63]
Hi,

I wanted to ask if it is possible to italicize the text displayed. I am trying to do something like this:
```lua
foo_component = {
  name = "foo",
  text = function()
    return { "foo", { "yellow", "ActiveBg", "bold,italic" } }
  end,
}
```
So I want the text ***foo*** to be displayed in bold-italic font. 

Unfortunately this doesn't work with my config (text is displayed in regular font). Changing it to plain "bold" however (like in the evil-line example) works just fine.

Am I missing something, or is "italic" / "bold,italic" text not yet supported?

**Comment by windwp** [comment]
It is not supported yet :).  
tmaybe you can create your own highlight and by nvim_set_hl and use that name on component.
that nvim_set_hl have a lot of options.  we only support fg,bg,bold.
