### ISSUE TITLE
LSP diagnostic failure

### ISSUE THREAD

**Issue by ray-x** [windwp/windline.nvim#7]
https://github.com/neovim/neovim/issues/14090

vim.lsp.diagnostcs moved to lsp.diagnostic

**Comment by windwp** [comment]
what do you mean about failure? i check and it still working

**Comment by ray-x** [comment]
I believe vim.lsp.diagnostic will be removed in the end. You can still use vim.lsp.diagnostic. But the support will be deprecated in the future releases. 

Check the document here:
https://github.com/neovim/neovim/blob/c2a65921d762929a1b8e740aeb92c7970d025736/runtime/doc/deprecated.txt#L68-L69

**Comment by windwp** [comment]
i think i will create a new branch for that.
i try to  run WindLineBenchmark and the lsp make it a little slower:(

**Comment by windwp** [comment]
@ray-x  you can checkout branch nightly

**Comment by windwp** [comment]
i use a new vim.diagnostic.get method the old get_count is slow

**Comment by ray-x** [comment]
thanks. I am not aware get_count is slow...

**Comment by windwp** [comment]
they removes a cache feature on that function,  it recalculates every time you call it. because we call it 4 times then it increase time.
