### ISSUE TITLE
FeatureRequest: allow trigger components refresh without cache

### ISSUE THREAD

**Issue by linrongbin16** [windwp/windline.nvim#71]
Please allow components refresh without cache.

I'm trying to integrate [lsp-progress.nvim](https://github.com/linrongbin16/lsp-progress.nvim) with windline, it already has builtin cache, and just return the message in `text` callback function will be fine.

But it seems no way to refresh the component using a 'User' event?

**Comment by windwp** [comment]
windline has component lsp progress
