### ISSUE TITLE
FeatureRequest: render icon color in `cache_file_type` component

### ISSUE THREAD

**Issue by linrongbin16** [windwp/windline.nvim#72]
<img width="365" alt="image" src="https://github.com/windwp/windline.nvim/assets/6496887/93a2b696-c686-4614-8a6b-422148cc50fc">

The 'nvim-web-devicons' plugin also returns the icon color (as 2nd returned value), please render the icon with that color.

**Comment by windwp** [comment]
check wiki it already supported on cache file icon
