### ISSUE TITLE
Themes `get_hl_color()` with new api can not get bg or fg color for link groups

### ISSUE THREAD

**Issue by 0x00-ketsu** [windwp/windline.nvim#74]
In `themes/init.lua` the function `M.get_hl_color()` with neovim api `vim.api.nvim_get_hl()` can not get bg or fg color for link groups.

![image](https://github.com/windwp/windline.nvim/assets/16932133/e377b7e8-5e87-4c67-b938-6c819fbff22f)

set option `link = false` will works fine.

```lua
local ok, hl = pcall(vim.api.nvim_get_hl, 0, { name = group_name, link = false })
```

![image](https://github.com/windwp/windline.nvim/assets/16932133/10a192b9-4e23-445f-95b1-96d2475e68be)

**Comment by windwp** [comment]
Thank.
